name: json_schema_to_freezed_openvn
description: An OpenVN-specific custom fork of json_schema_to_freezed - Convert JSON schema files to Dart classes with Freezed or regular Dart classes with JSON serialization support.
version: 0.1.0

publish_to: "none" # Remove this line if you want to publish to pub.dev
repository: https://github.com/Stefan4D/json_schema_to_freezed_openvn
homepage: https://github.com/Stefan4D/json_schema_to_freezed_openvn
documentation: https://github.com/Stefan4D/json_schema_to_freezed_openvn/blob/main/README.md
issue_tracker: https://github.com/Stefan4D/json_schema_to_freezed_openvn/issues

environment:
  sdk: ^3.7.2

executables:
  json_schema_to_freezed_openvn: bin/json_schema_to_freezed.dart

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.3.0
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
