name: json_schema_to_freezed
description: A command-line application to convert JSON Schema to Dart Freezed models.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.3.0
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
